services:
  frontend:
    # image: snibox/nginx-puma:1.15.9
    image: docker.lab.windix.au/nginx-puma:arm
    ports:
      - "8001:80"
    volumes:
      - static-files:/var/www/html
    depends_on:
      - backend

  backend:
    # image: snibox/snibox:latest
    image: docker.lab.windix.au/snibox:sqlite-arm64
    command: sh -c "rm -rf tmp/pids && ./bin/rails s -p 3000 -b '0.0.0.0'"
    environment:
      # DB_NAME: "${DB_NAME}"
      # DB_USER: "${DB_USER}"
      # DB_PASS: "${DB_PASS}"
      # DB_HOST: "${DB_HOST}"
      # DB_PORT: "${DB_PORT}"
      FORCE_SSL: "${FORCE_SSL}"
      MAILGUN_SMTP_PORT: "${MAILGUN_SMTP_PORT}"
      MAILGUN_SMTP_SERVER: "${MAILGUN_SMTP_SERVER}"
      MAILGUN_SMTP_LOGIN: "${MAILGUN_SMTP_LOGIN}"
      MAILGUN_SMTP_PASSWORD: "${MAILGUN_SMTP_PASSWORD}"
      MAILGUN_API_KEY: "${MAILGUN_API_KEY}"
      MAILGUN_DOMAIN: "${MAILGUN_DOMAIN}"
      MAILGUN_PUBLIC_KEY: "${MAILGUN_PUBLIC_KEY}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
    volumes:
      - static-files:/app/public
      - /data/appdata/snibox/storage:/app/storage
    # depends_on:
    #   - database

  # database:
  #   image: postgres:10.7-alpine
  #   volumes:
  #     - pg-data:/var/lib/postgresql/data

volumes:
  # pg-data:
  static-files:
